
- name: Create Virtual Network & Subnets
  hosts: localhost
  connection: local
  vars_files:
    - ~/github/ansible/1.3/vars.yaml
  tasks:
  - name: Create resource group {{ azure.vn_rg }}
    azure_rm_resourcegroup:
      name: "{{ azure.vn_rg }}"
      location: "{{ azure.vn_location }}"

  - name: Create a virtual network {{ azure.vn_name }}
    azure_rm_virtualnetwork:
      name: "{{ azure.vn_name }}"
      resource_group: "{{ azure.vn_rg }}"
      address_prefixes_cidr:
          - "{{ azure.vn_address }}"

  - name: Create subnet VLAN_EXTERNAL
    azure_rm_subnet:
      name: VLAN_EXTERNAL
      virtual_network_name: "{{ azure.vn_name }}"
      resource_group: "{{ azure.vn_rg }}"
      address_prefix_cidr: "{{ azure.vlan_ext }}"

  - name: Create subnet VLAN_INTERNAL
    azure_rm_subnet:
      name: VLAN_INTERNAL
      virtual_network_name: "{{ azure.vn_name }}"
      resource_group: "{{ azure.vn_rg }}"
      address_prefix_cidr: "{{ azure.vlan_int }}"

  - name: Create subnet VLAN_MGMT
    azure_rm_subnet:
      name: VLAN_MGMT
      virtual_network_name: "{{ azure.vn_name }}"
      resource_group: "{{ azure.vn_rg }}"
      address_prefix_cidr: "{{ azure.vlan_mgmt }}"
