
- name: STEP-01 Create Azure {{ ubuntu.vm_name | upper }}
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - ~/github/ansible/vault/vault.yaml
    - ~/github/ansible/1.3/vars.yaml
  tasks:
  - name: Create VM UBUNTU-0701
    include_tasks: pb-azure-vm-ubuntu.yaml

- name: STEP-02 Install Docker on Ubuntu host
  vars_files:
    - ~/github/ansible/1.3/vars.yaml
  hosts: "{{ ubuntu.vm_dnslabel }}.{{ azure.vn_location }}.cloudapp.azure.com"
  gather_facts: yes
  remote_user: azureuser
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
      - name: Install Docker
        include_tasks: pb-azure-vm-ubuntu-docker.yaml

- name: STEP-03 Pull Docker Image & Create Container
  vars_files:
    - ~/github/ansible/1.3/vars.yaml
  hosts: "{{ ubuntu.vm_dnslabel }}.{{ azure.vn_location }}.cloudapp.azure.com"
  gather_facts: no
  remote_user: azureuser
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
      - name: Pull Docker Image & Create Container
        include_tasks: pb-azure-vm-ubuntu-docker-container.yaml
